kind = "mobile"
previewPath = "/"
title = "AquaGuard - IoT Water Monitor"
version = "1.0.0"
id = "artifacts/water-monitor"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24731

[services.development]
run = "pnpm --filter @workspace/water-monitor run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/water-monitor", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/water-monitor", "run", "serve" ]

[services.env]
PORT = "24731"
BASE_PATH = "/"
