version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: smra
      POSTGRES_PASSWORD: smra
      POSTGRES_DB: smra
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local